language: c
  
os:
  - windows
  
branches:
  only:
    - deploy

compiler:
  - gcc
  
before_install:
  #- 
  
before_script:
  #there is no need to configure build toolchain since the platform on travis CI  
  #is windows and will come prebuilt with powershell, .NET platform, VBS and Batch

script:
  CronuxTestRunner.bat
  cd .\commands\
  $ ..\Cronux.bat genbuild ${..\Cronux.bat version}
  $ dir ..\build\1.1\
  #$ ls ..\build\${.\Cronux.bat version}\
  

  