language: c
  
os:
  - windows
  
# branches:
#   only:
#     - master
#     - deploy

compiler:
  - gcc
  
before_install:
  #- 
  
before_script:
  #there is no need to configure build toolchain since the platform on travis CI  
  #is windows and will come prebuilt with powershell, .NET platform, VBS and Batch

script:
  - ./CronuxTestRunner.bat
  - cd ./commands/
  - ./$.bat ../Cronux.bat genbuild ${../Cronux.bat version}
  - ./$.bat dir ../build/1.1/
  - #./$.bat ls ../build/${../Cronux.bat version}/
  

  