language: sh

os:
  - windows
  
before_install:
  - choco install pandoc
  - choco install python2
  - PATH=$PATH:C:/Python27/Scripts/
  - C:/Python27/Scripts/pip.exe install sphinx
  #- C:/Python27/Scripts/pip.exe install themata
  
before_script:
  - git config --local user.email "azeezadewale98@gmail.com"
  - git config --local user.name "Travis CI"

script:
  - mkdir dist/
  - cd dist/
  - git clone https://github.com/Thecarisma/themata.git
  - cd themata/
  - C:/Python27/Scripts/pip.exe install .
  - cd ../../
  - powershell -Command Set-ExecutionPolicy Bypass
  - powershell -Command $(pwd)/Cronux.bat docronux
  - cd dist/gh-pages/
  - C:/Python27/Scripts/sphinx-build.exe -b html -d build/doctrees  ./ build/html
  - cd ../../
  
deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - cd dist/
      - git clone https://github.com/Thecarisma/Cronux.wiki.git
      - cd Cronux.wiki/
      - cp -r ../wiki/* ./
      - git add .; git commit -m "Travis build=${TRAVIS_BUILD_NUMBER}. Update Wiki from Travis CI"
      #- git push https://Thecarisma:${GITHUB_TOKEN}@github.com/Thecarisma/Cronux.wiki.git HEAD:master;
      - cd ../../
    on:
       branch: master
  - provider: script
    skip_cleanup: true
    script: 
      - cd dist/
      - git clone -b gh-pages https://github.com/Thecarisma/Cronux.git
      - cd Cronux/
      - cp -r ../gh-pages/build/html/* ./
      - git add .; git commit -m "Travis build=${TRAVIS_BUILD_NUMBER}. Update Documentation from Travis CI"
      - git push https://Thecarisma:${GITHUB_TOKEN}@github.com/Thecarisma/Cronux.git HEAD:gh-pages;
      - cd ../../
    on:
       branch: master
