language: c

os:
  - windows
  
before_install:
  #- 
  
before_script:
  #there is no need to configure build toolchain since the platform on travis CI  
  #is windows and will come prebuilt with powershell, .NET platform, VBS and Batch

script:
  - echo $(pwd)
  - powershell -Command ls
  - powershell -Command Set-ExecutionPolicy Bypass
  - powershell -Command $(pwd)/Cronux.bat ps12markdown $(pwd)/commands/ $(pwd)/dist/cronux_doc/ -Recurse
  - powershell -Command ls $(pwd)/dist/cronux_doc/
  
deploy:
  # provider: pages
  # skip_cleanup: true
  # github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  # keep_history: true
  # local_dir: ./build/documentation/
  # on:
    # branch: master
  # provider: releases
  # skip_cleanup: true
  # api_key: $GITHUB_TOKEN
  # file_glob: true
  # file:
    # - "build/$(./Cronux.bat version)/Cronux.bat"
    # - "build/$(./Cronux.bat version)/Cronux.$(./Cronux.bat version).zip"
  # on:
    # tags: true
