language: c

os:
  - windows
  
before_install:
  #- 
  
before_script:
  #there is no need to configure build toolchain since the platform on travis CI  
  #is windows and will come prebuilt with powershell, .NET platform, VBS and Batch

script:
  - choco install pandoc
  - choco install python
  #- pip install themata
  - cd dist/
  - git clone https://github.com/Thecarisma/themata.git
  - cd themata/
  - pip install .
  - cd ../../
  - powershell -Command Set-ExecutionPolicy Bypass
  - powershell -Command $(pwd)/Cronux.bat docronux
  - cd dist/
  - git clone https://github.com/Thecarisma/Cronux.wiki.git
  - cd Cronux.wiki/
  - cp -r ../wiki/* ./
  - git config --local user.email "azeezadewale98@gmail.com"
  - git config --local user.name "Travis CI"
  - git add .; git commit -m "Travis build=${TRAVIS_BUILD_NUMBER}. Update Wiki from Travis CI"
  - git push https://Thecarisma:${GITHUB_TOKEN}@github.com/Thecarisma/Cronux.wiki.git HEAD:master;
  - cd ../../
  - cd dist/gh-pages/
  - powershell -Command ./make html
  - ls
  - cd ../../
  
deploy:
  # provider: pages
  # skip_cleanup: true
  # github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  # keep_history: true
  # local_dir: ./build/documentation/
  # on:
    # branch: master
  # provider: releases
  # skip_cleanup: true
  # api_key: $GITHUB_TOKEN
  # file_glob: true
  # file:
    # - "build/$(./Cronux.bat version)/Cronux.bat"
    # - "build/$(./Cronux.bat version)/Cronux.$(./Cronux.bat version).zip"
  # on:
    # tags: true
