<#
.SYNOPSIS
    
.DESCRIPTION
    
.INPUTS 
    
.OUTPUTS 
    
.NOTES
    Version    : 1.0
    File Name  : extractx.ps1
    Author     : Adewale Azeez - azeezadewale98@gmail.com
    Date       : Jan-06-2019
.LINK
    https://thecarisma.github.io/Cronux
.EXAMPLE
    Cronux buildcronux  1.0 ./commands/ ./dist/
    
.EXAMPLE
    
#>

Param(
    [Parameter(mandatory=$true)]
    [string]$export_list_path,
    [switch]$Application
)

$export_list_path = [System.IO.Path]::GetFullPath($export_list_path)
$export_list_path_dir = [System.IO.Path]::GetDirectoryName($export_list_path)
$count = 0

If ( -not [System.IO.Directory]::Exists($export_list_path_dir)) {
    [System.IO.Directory]::CreateDirectory($export_list_path_dir) > $null
    If ( -not $?) {
        Return
    }
}
"Preparing to export commands to $export_list_path"
[System.IO.File]::WriteAllLines("$export_list_path", 
"//All the Alias, Functions, Cmdlets preinstalled or exposed 
//through powershell. This is autogenerated by Cronux 
//<https://thecarisma.github.io/Cronux>
")

Get-Command * | ? { -not $_.Name.Contains("?") -and $_.CommandType -eq "Alias" -or $_.CommandType -eq "Function" -or $_.CommandType -eq "Cmdlet" -or ($Application -and $_.CommandType -eq "Application")} | Foreach-Object {
    [System.IO.File]::AppendAllText("$export_list_path", "$($_.Name)`n")
    $count++
}
"$count commands exported into $export_list_path"